### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by sunhay** [bsoung/musical-mash#1]
Hi!

Looks like this public repository has the SoundCloud intern challenge API keys hardcoded in plaintext. Mind removing this repository from GitHub for now? We'd like to make sure the key doesn't get leaked and abused.

Thanks,
Sunny

**Comment by bsoung** [comment]
Hey Sunhay,

I've made the repo private again - I checked the areas I used the API Key and they all refer to files that I have git ignored and have not uploaded to the directory. Could you let me know which file has the key hardcoded?

**Comment by bsoung** [comment]
Intern Challenge API key has been replaced with personal key and all keys have been left out of the repo via git ignore.
